create table if not exists public.respuestas_senior_activa (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  codigo_participante text not null,
  ciudad text,
  edad_mascota integer,
  especie text,
  atractivo text,
  intencion text,
  acepta_red_cerrada text,
  acepta_declaracion text,
  precio text,
  monto_mensual integer,
  monto_anual_descuento integer,
  importancia_teleorientacion text,
  importancia_chequeo_geriatrico text,
  importancia_desparasitacion text,
  importancia_vacuna_anual text,
  importancias_coberturas jsonb,
  cobertura_valiosa text,
  comentario text,
  mejora text,
  version_prototipo text,
  modalidad text,
  escenario_simulado text,
  valor_simulado integer,
  copago_simulado integer
);

alter table public.respuestas_senior_activa enable row level security;

create policy "permitir insertar respuestas anonimas"
on public.respuestas_senior_activa
for insert to anon
with check (true);

alter table public.respuestas_senior_activa
  add column if not exists monto_mensual integer,
  add column if not exists monto_anual_descuento integer,
  add column if not exists importancia_teleorientacion text,
  add column if not exists importancia_chequeo_geriatrico text,
  add column if not exists importancia_desparasitacion text,
  add column if not exists importancia_vacuna_anual text;

alter table public.respuestas_senior_activa
  add column if not exists importancias_coberturas jsonb;

