-- Crear tabla si no existe
CREATE TABLE IF NOT EXISTS public.respuestas_senior_activa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  codigo_participante TEXT NOT NULL,
  ciudad TEXT,
  edad_mascota INTEGER,
  estrato_socioeconomico INTEGER,
  edad_persona INTEGER,
  sexo_persona TEXT,
  genero TEXT,
  sexo_mascota TEXT,
  especie TEXT,
  atractivo TEXT,
  intencion TEXT,
  acepta_red_cerrada TEXT,
  acepta_declaracion TEXT,
  precio TEXT,
  monto_mensual INTEGER,
  monto_anual_descuento INTEGER,
  importancia_teleorientacion TEXT,
  importancia_chequeo_geriatrico TEXT,
  importancia_desparasitacion TEXT,
  importancia_vacuna_anual TEXT,
  importancias_coberturas JSONB,
  cobertura_valiosa TEXT,
  comentario TEXT,
  mejora TEXT,
  version_prototipo TEXT,
  modalidad TEXT,
  escenario_simulado TEXT,
  valor_simulado INTEGER,
  copago_simulado INTEGER
);

-- Habilitar RLS
ALTER TABLE public.respuestas_senior_activa ENABLE ROW LEVEL SECURITY;

-- Eliminar política anterior si existe
DROP POLICY IF EXISTS "permitir insertar respuestas anonimas" ON public.respuestas_senior_activa;

-- Crear política para permitir inserciones anónimas
CREATE POLICY "permitir_insertar_respuestas_anonimas"
ON public.respuestas_senior_activa
FOR INSERT
TO anon
WITH CHECK (true);

-- Permitir también a usuarios autenticados
CREATE POLICY "permitir_insertar_autenticados"
ON public.respuestas_senior_activa
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Crear índice para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_respuestas_fecha ON public.respuestas_senior_activa(fecha DESC);
CREATE INDEX IF NOT EXISTS idx_respuestas_codigo ON public.respuestas_senior_activa(codigo_participante);
